# site-config.yaml — Projektkonfiguration für Quarto-Kurswebsite
# Fülle in Ruhe aus

# --- Kurs Infos
course_code: "KURS-123"                                      # Potentieller Code LV-yyyy-yyy wird nur auf der Index Seite eingetragen
contact_email: "name@uni.de"                                 # kann abweichend oder gleich zu Impressum sein in der Regel Dozen*in wird nur auf der Index Seite eingetragen    
site_title: "your title"                                     # Name der Seite in der Titelleiste
org_name: "your organisation"                                # erscheint im Gegensatz zu chair_name etc im Footer  Header usw            
site_url: "https://your-github-name.github.io/your-repo"
repo_url: "https://github.com/your-github-name/your-repo"    
logo_path: "images/your-logo.png"                            # Logo obere Ecke Navbar

# Navbar rechts
portal_text: "Hotzenplotz"                     # z.B. Interne Lernplattform
portal_url: "Hotzenplotz"                      # https://www.ilias.uni-koeln.de/ilias/login.php?client_id=uk&cmd=force_login&lang=de

# Footer / Impressum-Link im Footer
impressum_href: "base/impressum.qmd"   # Script macht automatisch .html daraus

# --- Branding ---
# --- Vanilla = original theme ---
brand_hex: ""          # leer lassen
brand_hex_dark: ""     # leer lassen

# --- Auskommentieren um Branding Color zu aktivieren 
#brand_hex: "#008BFF"             # Light
#brand_hex_dark: "yes"            # optional (leer = wie Light)


brand_font: "system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Arial, sans-serif"
dark_theme: "yes"             # "yes" oder "no"

# --- Impressum / Datenschutz ---
responsible_name: "Hotzenplotz"                                        # z. B. "Prof. Dr. …"
responsible_address: " Zeile1 <br/> Zeile 2 <br/> Zeile 3"  # HTML-Zeilenumbruch mit <br />
responsible_email: "responsible@uni.de"                     # email der Impressum verantworlichen Person
uni_name: "Hotzenplotz"                                                # Name der Uni/Institution               
uni_url: "Hotzenplotz"                                                 # Hompage der Uni/Institution
institute_name: "Hotzenplotz"                                          # Name der Abteilung/Institut/Unterorganisation
institute_url: "Hotzenplotz"                                           # Hompage der Abteilung/Institut/Unterorganisation
chair_name: "Hotzenplotz"                                              # Name der AG
chair_url: "Hotzenplotz"                                               # Hompage der AG
imprint_url: "Hotzenplotz"                                             # offizielles Impressum der Organisation

