name: Quarto Build (HTML + DOCX + PDF)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ci-Profil erzwingt output-dir=docs (ohne Repo-Änderungen)
      - name: Create CI profile (output=docs)
        run: |
          cat > _quarto-profile-ci.yml <<'YML'
          project:
            output-dir: docs
          execute:
            freeze: false
          YML

      - name: Set up Quarto + TinyTeX
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Show versions
        run: |
          quarto --version
          pandoc --version | head -n 2
          tlmgr --version || true

      # WICHTIG: kein --to! So erzeugt Quarto HTML + alle format-links (PDF/DOCX)
      - name: Render site (HTML + alt formats via format-links)
        env:
          QUARTO_PROFILE: ci
        run: |
          quarto render . --log-level=INFO

      # Fallback: falls Profil ignoriert wird und nach _site/ gebaut wurde
      - name: Fallback _site -> docs
        run: |
          if [ -d "_site" ] && [ ! -f "docs/index.html" ]; then
            echo "Profile ignored; copying _site/ to docs/"
            rm -rf docs
            mkdir -p docs
            cp -a _site/. docs/
          fi

      - name: Sanity check
        run: |
          test -f docs/index.html || (echo "docs/index.html missing" && exit 1)
          echo "Listing alt formats found under docs/:"
          find docs -type f \( -name '*.pdf' -o -name '*.docx' \) -printf '%P\n' || true

      - name: Commit & push docs
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f docs
          git commit -m "CI: render site with alt formats (HTML+PDF+DOCX) [skip ci]" || echo "Nothing to commit"
          git push
